### ISSUE TITLE
Crit table rolls don't seem to account for luck modifier

### ISSUE THREAD

**Issue by DogaKilic** [sasquach45932/dcc-qol#10]
Hello, I was checking out the DCC system on foundry and really loved your module!
But while testing, I realized that the crit table rolls seem to not account for the luck modifier of the PC.
I tried it with a level 0 and a level 1 character and for both, regardless of the luck modifier, only the dice itself without any modifiers get rolled for crits.
Fumbles seem to work just fine and if I turn off the dcc-qol module, both fumbles and crits work correctly.

**Comment by sasquach45932** [comment]
Hello,

Please test it with the following [URL](https://github.com/sasquach45932/dcc-qol/releases/download/0.0.16/module.json).

**Comment by DogaKilic** [comment]
It works with the new url, thanks a lot 👍
