### ISSUE TITLE
Automated Deed Die rolling 11 times instead of just once

### ISSUE THREAD

**Issue by tonyrobots** [sasquach45932/dcc-qol#11]
Here's a weird one. I have "Attack Roll Bonus" in my Warrior sheet configured to "Manual Roll." Attack Bonus is set to "+d3". (note it breaks if set to "+1d3" -- should make more robust). In weapon attack and damage have "+@ab". When I roll an attack, instead of rolling a single d3 deed die, it rolls 11d3. 

![image](https://github.com/sasquach45932/dcc-qol/assets/178870/f0cea612-4582-4ae5-b293-b1a6cd1a1f62)

![image](https://github.com/sasquach45932/dcc-qol/assets/178870/f8002b59-0e73-4810-94e4-c8d08cdfe8ff)

![image](https://github.com/sasquach45932/dcc-qol/assets/178870/a771a4bd-0040-4e4b-a162-cb60ac1c5b59)

**Comment by tonyrobots** [comment]
Found the issue. Line 528 in patch.js:

`  const deedDie = this.system.details.attackBonus.replace('+', '1')`

Seems like the 1 is already there, so it's becoming 11d3. Changing this to replace with '' instead of '1' works correctly, at least given my data/setup.

**Comment by sasquach45932** [comment]
Fixed in [PR #12](https://github.com/sasquach45932/dcc-qol/pull/12).
Thank you [tonyrobots](https://github.com/tonyrobots)!
