### ISSUE TITLE
Ranged weapon damage causes error

### ISSUE THREAD

**Issue by r0guebyte** [sasquach45932/dcc-qol#3]
When a ranged weapon hits and there is a "Damage" button in the chat, it causes an error in the console and nothing happens in the interface.

Tried this off a wizard and fighter character sheet.  

actor.js:1127 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'system')
[Detected 2 packages: system:dcc, dcc-qol]
    at DCCActor.rollDamage (actor.js:1127:26)
    at HTMLButtonElement.ChatCardAction (chat.js:45:42)
    at HTMLElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
rollDamage @ actor.js:1127
ChatCardAction @ chat.js:45
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
await in y.handle (async)
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by sasquach45932** [comment]
Which version of the dcc system  are you using?
Could you attach the JSON of the  attacker actor,  please? An let me know the weapon as well.

During the attack roll the attacker's weaponID is stored in the chat card. It seems it is missing or the weapon was deleted. Could it have happened?

**Comment by r0guebyte** [comment]
Foundry V11 Build 313
Dungeon Crawl Classics 0.39.1
DCC Core Book Compendium 1.0.6
DCC QOL 0.0.10

Tried attacking with the Crossbow, which I dragged over from the compendium, and "New Weapon", which I did as a quick add off the character sheet.

No, the weapons is still on the character sheet.  The attached example is a fresh import from Purple Sorcerer, an item dragged from compendium and item added off the sheet.  This is only happening with ranged attacks.

[fvtt-Actor-indentured-servant-60b0eqgxozg8Trjn.json](https://github.com/sasquach45932/dcc-qol/files/12917005/fvtt-Actor-indentured-servant-60b0eqgxozg8Trjn.json)

**Comment by sasquach45932** [comment]
Fixed in 0.0.11.
Please remove dcc-qol and install it using URL: https://github.com/sasquach45932/dcc-qol/releases/latest/download/module.json.
Let me know the test result if it is ok, update will be available on  foundryvtt.com as well.

**Comment by r0guebyte** [comment]
Just installed and tested, damage rolls work as expected.

Thanks for the quick turn around!
