### ISSUE TITLE
Luck mod not affecting monster crits

### ISSUE THREAD

**Issue by Defiantweb** [sasquach45932/dcc-qol#5]
Edit: Seem to work fine/ as intended. Sorry. Turns out that if after a monster rolls a crit vs a PC, if I have the PC token selected when click the crit button on the chat card, it rolls the crit as the selected token, no the monster that originally made that attack. So the luck mod is not applied in case that because the selected token's target didn't have a luck mod! I'll just have to be careful to make sure I keep the monster's token selected before I make its crit roll.

**Comment by sasquach45932** [comment]
Please install manually with the following [URL](https://github.com/sasquach45932/dcc-qol/releases/download/0.0.13/module.json)  and test it. Let me know the result.

**Comment by sasquach45932** [comment]
Fixed in 0.13
