### ISSUE TITLE
User lacks permission to update ActorDelta

### ISSUE THREAD

**Issue by ericroussille** [sasquach45932/dcc-qol#6]
When I check "Auto apply damages" in module configuration and I roll an attack that does damage and click on damage button in the chat window, I get the error popup message "User XXX lacks permission to update ActorDelta [YYYY] in parent token [ZZZZ]". The dice damage is rolled but the result does not apply on the target's HP.

Here are the traces in the log.

 User XXX lacks permission to update ActorDelta [UyzKltXZE1L6VJ8t] in parent Token [J2yxU0rd05FnlHu3] [foundry.js:68326:78](https://192.168.0.3:30000/scripts/foundry.js)
    fetch foundry.js:68326
    notify foundry.js:68223
    error foundry.js:68260
    _handleError foundry.js:3468
    dispatch foundry.js:3450
    value socket.js:532
    value socket.js:459
    emit index.mjs:136
    value manager.js:207
Uncaught (in promise) Error: User XXX lacks permission to update ActorDelta [UyzKltXZE1L6VJ8t] in parent Token [J2yxU0rd05FnlHu3]
[No packages detected]

This error message does not appear when I uncheck  "Auto apply damages" in module configuration

**Comment by sasquach45932** [comment]
What is your user role?
![image](https://github.com/sasquach45932/dcc-qol/assets/92884040/7db81134-6219-4dd4-a90c-e26d4ebbc440)

**Comment by Defiantweb** [comment]
I'm experiencing the same issue. Did not notice it when I was doing my testing logged in as Gamemaster, but tonight when I had all my players logged in for session zero test they all had this issue. I just duplicated it on my own machine logged in as a test player. "Player" is the role in all cases. Is there some permission I need to set? Letting players update tokens did not do the trick.

**Comment by Defiantweb** [comment]
To be clear, damage is applied correctly to owned tokens, but players vs other players or NPC tokens throws that error

**Comment by sasquach45932** [comment]
I have to think it over how to fix it. Damage apply code part should run as GM so socketlib module  or using Foundry sockets might be the solution.

**Comment by Defiantweb** [comment]
I have heard the Midi Quality of Life module for 5e does it that way. Maybe
you could peek at their code?

**Comment by sasquach45932** [comment]
Please install manually with the following [URL](https://github.com/sasquach45932/dcc-qol/releases/download/0.0.13/module.json) and test it. Let me know the result.

**Comment by ericroussille** [comment]
I have tested this V13. It works. Great work !

**Comment by Defiantweb** [comment]
I just tested it via the URL you linked (show as version 0.0.13) and while I no longer see the error notification, the damage is still not being applied when I log in as a player and attack an NPC. When logged in as Gamemaster, everything works as expected, no problem. Wondering how it is that eric had a different result? is there a cache I need to flush or something?

**Comment by sasquach45932** [comment]
Gamemaster needs to be connected as damage apply happens on  its client.

**Comment by sasquach45932** [comment]
Fixed in 0.13

**Comment by sasquach45932** [comment]
Fixed in 0.13
