### ISSUE TITLE
Thief Backstab always hits

### ISSUE THREAD

**Issue by Digmarx** [sasquach45932/dcc-qol#9]
With the DCC-QOL module enabled, all attack rolls made via the thief's backstab are reported as hits. Note that I haven't disabled any other modules or anything to test this.

@tonyrobots has apparently submitted a pull request for a fix.

**Comment by tonyrobots** [comment]
Yes, "crit" flag was being set for all backstabs, which meant all backstabs were hitting -- adjusted so that it requires the attack roll (with backstab bonus) to be successful. ( https://github.com/sasquach45932/dcc-qol/pull/8 )
